
version: 2
jobs:
    "java":
        docker:
          - image: circleci/openjdk:8-jdk
          
        working_directory: ~/repo

        environment:
          JVM_OPTS: -Xmx3200m
          TERM: dumb

        steps:
          - checkout

          - restore_cache:
              keys:
              - v2-dependencies-{{ checksum "build.gradle" }}
              - v2-dependencies-

          - run: 'gradle dependencies'

          - save_cache:
              paths:
                - ~/.gradle
              key: v2-dependencies-{{ checksum "build.gradle" }}

          - run: 'gradle clean build'
          - run: 'gradle shadowJar'

          - store_artifacts:
              path: 'fmu-proxy/build/libs/fmu-proxy.jar'
              destination: 'fmu-proxy.jar'

workflows:
    version: 2
    build:
        jobs: 
            - "java"
